### ISSUE TITLE
Performance issue of slice() function

### ISSUE THREAD

**Issue by tuyennhv** [achingbrain/uint8arraylist#24]
Profiling from https://github.com/ChainSafe/lodestar/pull/4114 shows a significant time was used for Uint8Array memory allocation

![](https://cdn.discordapp.com/attachments/999983088769708082/1000322094397128775/Screen_Shot_2022-07-23_at_15.38.34.png)

With a 5-minute profile, it takes 16% of cpu time just for this function.

This is mostly called form "slice()` function as shown in https://github.com/libp2p/js-libp2p/issues/1303

**Comment by achingbrain** [comment]
@tuyennhv what sort of size of length-prefixed data are you seeing consume all this time during your profiling?  Is it a few bytes on average or more like megabytes?

**Comment by tuyennhv** [comment]
> @tuyennhv what sort of size of length-prefixed data are you seeing consume all this time during your profiling? Is it a few bytes on average or more like megabytes?

I'm not able to debug the length-prefixed data as uint8arraylist is used in different consumers, but the one thing I notice is >90% of the time `slice()` function spanning exactly 1 buffer and right now we do the copy of that 1 buffer  unnecessarily in `concat()` function. If we do early return in that case (without calling `concat` of an array of 1 item) then I get through this issue.

In `bl.slice` api spec, it said that:
```
If the requested range spans a single internal buffer then a slice of that buffer will be returned which shares the original memory range of that Buffer. If the range spans multiple buffers then copy operations will likely occur to give you a uniform Buffer.
```

**Comment by achingbrain** [comment]
> If we do early return in that case

This optimisation is now [included in the `.subarray` method](https://github.com/achingbrain/uint8arraylist/blob/master/src/index.ts#L200-L202).  It's in `.subarray` as that per `Uint8Array` semantics it should be no-copy (when possible), and not `.slice` as that should always be copy.

> In bl.slice api spec, it said that:

bl follows semantics derived from node `Buffer`, this module follows semantics derived from `Uint8Array` which are ever-so-slightly-different-yet-also-completely-incompatible  on this point.
