### ISSUE TITLE
toUint8Array() is not defined

### ISSUE THREAD

**Issue by paralin** [achingbrain/uint8arraylist#32]
```
.toUint8Array()
```

Defined in the README.md but not in the codebase.

**Comment by achingbrain** [comment]
Good spot, you should use `.slice` for a `Uint8Array` containing copy of the list contents , `.subarray` for a no-copy `Uint8Array` (if possible e.g. the if the list is only made up of one `Uint8Array` internally) or `.subarray` for a no-copy as a `Uint8ArrayList`.

Would you like to PR an update to the README?

**Comment by paralin** [comment]
@achingbrain https://github.com/achingbrain/uint8arraylist/blob/daa6b74ee19e5f2078d0446100b6c8b29dee2430/src/index.ts#L169

.slice doesn't copy in all cases, right?

**Comment by achingbrain** [comment]
That line is from the `.subarray` method, not `.slice`.  The last line of `.slice` concats all the `Uint8Array`s together, which returns a new array with the contents so is a copy operation.

**Comment by paralin** [comment]
Ok, thanks for clearing that up.

**Comment by paralin** [comment]
See #38
